import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createHash } from 'node:crypto';

const script = fs.readFileSync(new URL('../deploy/prepare-runner-account-20260831-02.sh', import.meta.url), 'utf8');
const embedded = /<<'CPP_ACCOUNT_NODE'\n([\s\S]+)\nCPP_ACCOUNT_NODE\n$/.exec(script);
assert.ok(embedded);
const { nssSnapshot, assertNssUnchanged } = await import('data:text/javascript;base64,' + Buffer.from(embedded[1]).toString('base64'));
const file = '/etc/nsswitch.conf';
const target = '/etc/authselect/nsswitch.conf';
const content = '# Generated by authselect; do not change.\npasswd: files sss\ngroup: files sss\n';
function stat(type, extra = {}) {
  return { uid: 0, gid: 0, nlink: 1, mode: type === 'link' ? 0o777 : type === 'directory' ? 0o755 : 0o644, size: Buffer.byteLength(content), isSymbolicLink: () => type === 'link', isFile: () => type === 'file', isDirectory: () => type === 'directory', ...extra };
}
function fixture(linked = true) {
  const entries = new Map([['/etc', stat('directory')], ['/etc/authselect', stat('directory')], [file, stat(linked ? 'link' : 'file')], [target, stat('file')]]);
  const state = { link: target, content: Buffer.from(content), resolved: linked ? target : file, reads: [] };
  const io = {
    lstatSync(name) { assert.ok(entries.has(name), 'unexpected file metadata read: ' + name); return entries.get(name); },
    realpathSync(name) { return name === file ? state.resolved : name; },
    readlinkSync(name) { assert.equal(name, file); return state.link; },
    readFileSync(name) { assert.equal(name, linked ? target : file); state.reads.push(name); return state.content; }
  };
  return { entries, state, io };
}

test('复现原脚本拒绝服务器已确认的 authselect 链接，02 版接受并记录目标摘要', () => {
  const original = fs.readFileSync(new URL('../deploy/prepare-runner-account-20260831.sh', import.meta.url), 'utf8');
  const regular = original.match(/function regular\(file\) \{[\s\S]+?\n\}\n(?=function directory)/)[0];
  const { io, state } = fixture();
  const before = new Function('fs', 'ensure', regular + '\nreturn regular;')(io, (ok, code) => { if (!ok) throw Object.assign(new Error(), { code }); });
  assert.throws(() => before(file), { code: 'NOT_REGULAR_FILE' });
  const snapshot = nssSnapshot(io);
  assert.equal(snapshot.target, target);
  assert.equal(snapshot.linkText, target);
  assert.equal(snapshot.sha256, createHash('sha256').update(content).digest('hex'));
  assert.equal(snapshot.entry.mode, 0o777);
  assert.deepEqual(state.reads, [target]);
  assert.doesNotThrow(() => assertNssUnchanged(snapshot, io));
});

test('同一固定目标的相对链接和原有普通文件形式均可检查', () => {
  const relative = fixture();
  relative.state.link = 'authselect/nsswitch.conf';
  assert.equal(nssSnapshot(relative.io).linkText, relative.state.link);
  const regular = fixture(false);
  assert.equal(nssSnapshot(regular.io).target, file);
  assert.equal(nssSnapshot(regular.io).linkText, null);
});

test('拒绝任意目标，且不先读取未知目标内容', () => {
  for (const unexpected of ['/tmp/nsswitch.conf', '/etc/authselect/user-nsswitch.conf', '../../home/apphttp/nsswitch.conf']) {
    const { state, io } = fixture();
    state.link = unexpected;
    assert.throws(() => nssSnapshot(io), { code: 'NSS_LINK_TARGET_UNEXPECTED' });
    assert.deepEqual(state.reads, []);
  }
});

test('拒绝非 root 所有的入口或入口硬链接', () => {
  for (const extra of [{ uid: 995 }, { nlink: 2 }]) {
    const { entries, io } = fixture();
    entries.set(file, stat('link', extra));
    assert.throws(() => nssSnapshot(io), { code: 'NSS_ENTRY_UNSAFE' });
  }
});

test('父目录必须是 root 所有、不可由组或其他用户写入的真实目录', () => {
  for (const name of ['/etc', '/etc/authselect']) {
    for (const value of [stat('directory', { uid: 995 }), stat('directory', { mode: 0o775 }), stat('link')]) {
      const { entries, io } = fixture();
      entries.set(name, value);
      assert.throws(() => nssSnapshot(io), { code: 'NSS_DIRECTORY_UNSAFE' });
    }
  }
});

test('目标拒绝再次链接、硬链接、非 root 所有、不安全权限及超大文件', () => {
  for (const value of [stat('link'), stat('directory'), stat('file', { nlink: 2 }), stat('file', { uid: 995 }), stat('file', { mode: 0o664 }), stat('file', { mode: 0o646 }), stat('file', { size: 262145 })]) {
    const { entries, io, state } = fixture();
    entries.set(target, value);
    assert.throws(() => nssSnapshot(io), { code: 'NSS_TARGET_UNSAFE' });
    assert.deepEqual(state.reads, []);
  }
});

test('拒绝与链接文字不一致的实际解析路径', () => {
  const { state, io } = fixture();
  state.resolved = '/tmp/nsswitch.conf';
  assert.throws(() => nssSnapshot(io), { code: 'NSS_LINK_TARGET_UNEXPECTED' });
  assert.deepEqual(state.reads, []);
});

test('普通文件仍拒绝可被普通用户改写的权限', () => {
  const { entries, io } = fixture(false);
  entries.set(file, stat('file', { mode: 0o666 }));
  assert.throws(() => nssSnapshot(io), { code: 'NSS_TARGET_UNSAFE' });
});

test('仍只接受默认或单条 files 用户映射来源，不因兼容链接放宽来源检查', () => {
  const { state, io } = fixture();
  state.content = Buffer.from(content + '\nsubid: files # local mapping\n');
  assert.doesNotThrow(() => nssSnapshot(io));
  for (const value of ['subid: sss\n', 'subid: files sss\n', 'subid: files\nsubid: files\n']) {
    state.content = Buffer.from(content + value);
    assert.throws(() => nssSnapshot(io), { code: 'SUBID_SOURCE_NOT_FILES' });
  }
});

test('操作前后必须保留 NSS 内容的每个字节，包括注释与换行', () => {
  const { state, io } = fixture();
  const before = nssSnapshot(io);
  for (const changed of [content.replace('do not change', 'changed'), content.replaceAll('\n', '\r\n'), content + '\n']) {
    state.content = Buffer.from(changed);
    assert.throws(() => assertNssUnchanged(before, io), { code: 'NSS_CONFIGURATION_CHANGED' });
  }
});

test('即使内容和最终目标相同，链接文字改变也会停止后续流程', () => {
  const { state, io } = fixture();
  const before = nssSnapshot(io);
  state.link = 'authselect/nsswitch.conf';
  assert.throws(() => assertNssUnchanged(before, io), { code: 'NSS_CONFIGURATION_CHANGED' });
});

test('NSS 权限或组归属改变不能被内容摘要掩盖', () => {
  for (const [name, extra] of [[file, { gid: 992 }], [target, { mode: 0o640 }], [target, { gid: 992 }]]) {
    const { entries, io } = fixture();
    const before = nssSnapshot(io);
    entries.set(name, stat(name === file ? 'link' : 'file', extra));
    assert.throws(() => assertNssUnchanged(before, io), { code: 'NSS_CONFIGURATION_CHANGED' });
  }
});
